name: Publicēt Profilu studiju

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Saņemt lapas failus
        uses: actions/checkout@v5
      - name: Sagatavot GitHub Pages
        uses: actions/configure-pages@v5
      - name: Iepakot statisko lapu
        uses: actions/upload-pages-artifact@v5
        with:
          path: .
      - name: Publicēt
        id: deployment
        uses: actions/deploy-pages@v5
